<?php

namespace SmartDato\FedEx\Enums;

enum MaskedDataEnum: string
{
    case CUSTOMS_VALUE = 'CUSTOMS_VALUE';
    case SHIPPER_ACCOUNT_NUMBER = 'SHIPPER_ACCOUNT_NUMBER';
    case DIMENSIONS = 'DIMENSIONS';
    case DUTIES_AND_TAXES_PAYOR_ACCOUNT_NUMBER = 'DUTIES_AND_TAXES_PAYOR_ACCOUNT_NUMBER';
    case INSURED_VALUE = 'INSURED_VALUE';
    case SECONDARY_BARCODE = 'SECONDARY_BARCODE';
    case SHIPPER_INFORMATION = 'SHIPPER_INFORMATION';
    case TERMS_AND_CONDITIONS = 'TERMS_AND_CONDITIONS';
    case TOTAL_WEIGHT = 'TOTAL_WEIGHT';
    case TRANSPORTATION_CHARGES_PAYOR_ACCOUNT_NUMBER = 'TRANSPORTATION_CHARGES_PAYOR_ACCOUNT_NUMBER';
}
