<?php

namespace SmartDato\FedEx\Enums;

enum ShipDocumentTypeEnum: string
{
    case CERTIFICATE_OF_ORIGIN = 'CERTIFICATE_OF_ORIGIN';
    case COMMERCIAL_INVOICE = 'COMMERCIAL_INVOICE';
    case ETD_LABEL = 'ETD_LABEL';
    case OTHER = 'OTHER';
    case PRO_FORMA_INVOICE = 'PRO_FORMA_INVOICE';
    case USMCA_CERTIFICATION_OF_ORIGIN = 'USMCA_CERTIFICATION_OF_ORIGIN';
    case USMCA_COMMERCIAL_INVOICE_CERTIFICATION_OF_ORIGIN = 'USMCA_COMMERCIAL_INVOICE_CERTIFICATION_OF_ORIGIN';
}
