<?php

namespace SmartDato\FedEx\Enums;

enum ShipmentSpecialServiceTypeEnum: string
{
    case APPOINTMENT = 'APPOINTMENT';
    case BROKER_SELECT_OPTION = 'BROKER_SELECT_OPTION';
    case CALL_BEFORE_DELIVERY = 'CALL_BEFORE_DELIVERY';
    case COD = 'COD';
    case CUSTOM_DELIVERY_WINDOW = 'CUSTOM_DELIVERY_WINDOW';
    case CUT_FLOWERS = 'CUT_FLOWERS';
    case DO_NOT_BREAK_DOWN_PALLETS = 'DO_NOT_BREAK_DOWN_PALLETS';
    case DO_NOT_STACK_PALLETS = 'DO_NOT_STACK_PALLETS';
    case DRY_ICE = 'DRY_ICE';
    case EAST_COAST_SPECIAL = 'EAST_COAST_SPECIAL';
    case EXCLUDE_FROM_CONSOLIDATION = 'EXCLUDE_FROM_CONSOLIDATION';
    case EXTREME_LENGTH = 'EXTREME_LENGTH';
    case INSIDE_DELIVERY = 'INSIDE_DELIVERY';
    case INSIDE_PICKUP = 'INSIDE_PICKUP';
    case INTERNATIONAL_CONTROLLED_EXPORT_SERVICE = 'INTERNATIONAL_CONTROLLED_EXPORT_SERVICE';
    case FEDEX_ONE_RATE = 'FEDEX_ONE_RATE';
    case THIRD_PARTY_CONSIGNEE = 'THIRD_PARTY_CONSIGNEE';
    case ELECTRONIC_TRADE_DOCUMENTS = 'ELECTRONIC_TRADE_DOCUMENTS';
    case FOOD = 'FOOD';
    case HOLD_AT_LOCATION = 'HOLD_AT_LOCATION';
    case INTERNATIONAL_TRAFFIC_IN_ARMS_REGULATIONS = 'INTERNATIONAL_TRAFFIC_IN_ARMS_REGULATIONS';
    case LIFTGATE_DELIVERY = 'LIFTGATE_DELIVERY';
    case LIFTGATE_PICKUP = 'LIFTGATE_PICKUP';
    case LIMITED_ACCESS_DELIVERY = 'LIMITED_ACCESS_DELIVERY';
    case LIMITED_ACCESS_PICKUP = 'LIMITED_ACCESS_PICKUP';
    case OVER_LENGTH = 'OVER_LENGTH';
    case PENDING_SHIPMENT = 'PENDING_SHIPMENT';
    case PHARMACY_DELIVERY = 'PHARMACY_DELIVERY';
    case POISON = 'POISON';
    case HOME_DELIVERY_PREMIUM = 'HOME_DELIVERY_PREMIUM';
    case PROTECTION_FROM_FREEZING = 'PROTECTION_FROM_FREEZING';
    case RETURNS_CLEARANCE = 'RETURNS_CLEARANCE';
    case RETURN_SHIPMENT = 'RETURN_SHIPMENT';
    case SATURDAY_DELIVERY = 'SATURDAY_DELIVERY';
    case SATURDAY_PICKUP = 'SATURDAY_PICKUP';
    case EVENT_NOTIFICATION = 'EVENT_NOTIFICATION';
    case DELIVERY_ON_INVOICE_ACCEPTANCE = 'DELIVERY_ON_INVOICE_ACCEPTANCE';
    case TOP_LOAD = 'TOP_LOAD';
    case FREIGHT_GUARANTEE = 'FREIGHT_GUARANTEE';
}
